# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/barry/Downloads/interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(551, 605)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setStyleSheet("background-color: rgb(84, 84, 84);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 0, 531, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.chat_history = QtWidgets.QListWidget(self.centralwidget)
        self.chat_history.setGeometry(QtCore.QRect(10, 70, 531, 461))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.chat_history.setFont(font)
        self.chat_history.setStyleSheet("color: rgb(255, 255, 255);\n"
                                        "background-color: rgb(35, 35, 35);\n"
                                        "border-radius: 5px;")
        self.chat_history.setObjectName("chat_history")
        self.start = QtWidgets.QPushButton(self.centralwidget)
        self.start.setGeometry(QtCore.QRect(10, 540, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.start.setFont(font)
        self.start.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.start.setStyleSheet("QPushButton {\n"
                                 "    color: rgb(255, 255, 255);\n"
                                 "    background-color: rgb(35, 35, 35);\n"
                                 "    border-radius: 5px;\n"
                                 "}\n"
                                 "QPushButton:hover{\n"
                                 "    background-color: rgb(0, 0, 0);\n"
                                 "}\n"
                                 "QPushButton:pressed{\n"
                                 "    background-color: rgb(255, 255, 255);\n"
                                 "    color: rgb(0, 0, 0);\n"
                                 "}")
        self.start.setObjectName("start")
        self.stop = QtWidgets.QPushButton(self.centralwidget)
        self.stop.setGeometry(QtCore.QRect(360, 540, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.stop.setFont(font)
        self.stop.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.stop.setStyleSheet("QPushButton {\n"
                                "    color: rgb(255, 255, 255);\n"
                                "    background-color: rgb(35, 35, 35);\n"
                                "    border-radius: 5px;\n"
                                "}\n"
                                "QPushButton:hover{\n"
                                "    background-color: rgb(0, 0, 0);\n"
                                "}\n"
                                "QPushButton:pressed{\n"
                                "    background-color: rgb(255, 255, 255);\n"
                                "    color: rgb(0, 0, 0);\n"
                                "}")
        self.stop.setObjectName("stop")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Voice Assistant"))
        self.start.setText(_translate("MainWindow", "Слушать"))
        self.stop.setText(_translate("MainWindow", "Стоп"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
